//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;


namespace IconicSku.Web
{
	#region Contexts

	/// <summary>
	/// No Metadata Documentation available.
	/// </summary>
	public partial class VXReportsEntities : ObjectContext
	{
		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		/// <param name="sku_id">No Metadata Documentation available.</param>
		public ObjectResult<KeyValuePair> GetIconicSkuProperties()
		{
			ObjectParameter sku_idParameter;
			if (sku_id.HasValue)
			{
				sku_idParameter = new ObjectParameter("sku_id", sku_id);
			}
			else
			{
				sku_idParameter = new ObjectParameter("sku_id", typeof(global::System.Int32));
			}

			return base.ExecuteFunction<KeyValuePair>("GetIconicSkuProperties", sku_idParameter);
		}
	}


	#endregion

}
