//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutaParser.Tests.Syntactic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Syntactic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syntactic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutaParser.Tests.Syntactic.Syntactic", typeof(Syntactic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum Color
        ///{
        ///   Red,
        ///   Green,
        ///   Blue
        ///}.
        /// </summary>
        internal static string EnumDeclaration1 {
            get {
                return ResourceManager.GetString("EnumDeclaration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum Color: long
        ///{
        ///   Red,
        ///   Green,
        ///   Blue
        ///}.
        /// </summary>
        internal static string EnumDeclaration2 {
            get {
                return ResourceManager.GetString("EnumDeclaration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum Color: uint
        ///{
        ///   Red = -1,
        ///   Green = -2,
        ///   Blue = -3
        ///}.
        /// </summary>
        internal static string EnumDeclaration3 {
            get {
                return ResourceManager.GetString("EnumDeclaration3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum Color 
        ///{
        ///   Red,
        ///   Green,
        ///   Blue,
        ///
        ///   Max = Blue
        ///}.
        /// </summary>
        internal static string EnumDeclaration4 {
            get {
                return ResourceManager.GetString("EnumDeclaration4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface C&lt;out X, in Y, Z&gt; 
        ///{
        ///  X M(Y y);
        ///  Z P { get; set; }
        ///}.
        /// </summary>
        internal static string InterfaceDeclaration1 {
            get {
                return ResourceManager.GetString("InterfaceDeclaration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface IControl
        ///{
        ///   void Paint();
        ///}.
        /// </summary>
        internal static string InterfaceDeclaration2 {
            get {
                return ResourceManager.GetString("InterfaceDeclaration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface IListBox: IControl
        ///{
        ///   void SetItems(string[] items);
        ///}.
        /// </summary>
        internal static string InterfaceDeclaration3 {
            get {
                return ResourceManager.GetString("InterfaceDeclaration3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface IComboBox: ITextBox, IListBox { }.
        /// </summary>
        internal static string InterfaceDeclaration4 {
            get {
                return ResourceManager.GetString("InterfaceDeclaration4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public interface IStringList
        ///{
        ///   void Add(string s);
        ///   int Count { get; }
        ///   event StringListEvent Changed;
        ///   string this[int index] { get; set; }
        ///}.
        /// </summary>
        internal static string InterfaceDeclaration5 {
            get {
                return ResourceManager.GetString("InterfaceDeclaration5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface I&lt;out T&gt; { void M&lt;U&gt;() where U : T; }.
        /// </summary>
        internal static string InterfaceDeclaration6 {
            get {
                return ResourceManager.GetString("InterfaceDeclaration6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface IList&lt;T&gt;
        ///{
        ///   T[] GetElements();
        ///}.
        /// </summary>
        internal static string InterfaceDeclaration7 {
            get {
                return ResourceManager.GetString("InterfaceDeclaration7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface IDictionary&lt;K,V&gt;
        ///{
        ///   V this[K key] { get; }
        ///   void Add(K key, V value);
        ///}.
        /// </summary>
        internal static string InterfaceDeclaration8 {
            get {
                return ResourceManager.GetString("InterfaceDeclaration8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface I&lt;A,B,C&gt;
        ///{
        ///   void F&lt;T&gt;(T t) where T: A;
        ///   void G&lt;T&gt;(T t) where T: B;
        ///   void H&lt;T&gt;(T t) where T: C;
        ///}.
        /// </summary>
        internal static string InterfaceDeclaration9 {
            get {
                return ResourceManager.GetString("InterfaceDeclaration9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers select c.Name.
        /// </summary>
        internal static string QueryExpression1 {
            get {
                return ResourceManager.GetString("QueryExpression1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers orderby c.LastName, c.FirstName select c.Name.
        /// </summary>
        internal static string QueryExpression10 {
            get {
                return ResourceManager.GetString("QueryExpression10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers orderby c.LastName descending, c.FirstName ascending select c.Name.
        /// </summary>
        internal static string QueryExpression11 {
            get {
                return ResourceManager.GetString("QueryExpression11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers orderby c.LastName descending, c.FirstName ascending orderby c.Address select c.Name.
        /// </summary>
        internal static string QueryExpression12 {
            get {
                return ResourceManager.GetString("QueryExpression12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers group c by c.Country.
        /// </summary>
        internal static string QueryExpression13 {
            get {
                return ResourceManager.GetString("QueryExpression13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers group c by c.Country into g select g.Key.
        /// </summary>
        internal static string QueryExpression14 {
            get {
                return ResourceManager.GetString("QueryExpression14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from itm in new int[] { 1, 2, 3, 4, 5 } let i = itm == 1 ? 1 : 0 select i.
        /// </summary>
        internal static string QueryExpression15 {
            get {
                return ResourceManager.GetString("QueryExpression15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from b in new int[] { 1, 2, 3, 4, 5 } where true &amp;&amp; (b.Equals) select b.
        /// </summary>
        internal static string QueryExpression16 {
            get {
                return ResourceManager.GetString("QueryExpression16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from b in new int[] { 1, 2, 3, 4, 5 } where true || (b.Equals) select b.
        /// </summary>
        internal static string QueryExpression17 {
            get {
                return ResourceManager.GetString("QueryExpression17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from b in new int[] { 1, 2, 3, 4, 5 } where true != (b.Equals) select b.
        /// </summary>
        internal static string QueryExpression18 {
            get {
                return ResourceManager.GetString("QueryExpression18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from int[] c in customers select c.Count.
        /// </summary>
        internal static string QueryExpression2 {
            get {
                return ResourceManager.GetString("QueryExpression2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from int[] c in customers from d in deltas select c.Count + d.
        /// </summary>
        internal static string QueryExpression3 {
            get {
                return ResourceManager.GetString("QueryExpression3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers let address = c.Address let area = c.PhoneNumber.AreaCode select address + area.
        /// </summary>
        internal static string QueryExpression4 {
            get {
                return ResourceManager.GetString("QueryExpression4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers join a in address on c.ZipCode equals a.ZipCode select c.Name.
        /// </summary>
        internal static string QueryExpression5 {
            get {
                return ResourceManager.GetString("QueryExpression5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers join a in address on c.ZipCode equals a.ZipCode into g select c.Name.
        /// </summary>
        internal static string QueryExpression6 {
            get {
                return ResourceManager.GetString("QueryExpression6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers join a in address on c.ZipCode equals a.ZipCode join n in phonenumber on c.AreaCode equals n.AreaCode into x select c.Name.
        /// </summary>
        internal static string QueryExpression7 {
            get {
                return ResourceManager.GetString("QueryExpression7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers orderby c.LastName select c.Name.
        /// </summary>
        internal static string QueryExpression8 {
            get {
                return ResourceManager.GetString("QueryExpression8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from c in customers orderby c.LastName ascending select c.Name.
        /// </summary>
        internal static string QueryExpression9 {
            get {
                return ResourceManager.GetString("QueryExpression9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch (i) {
        ///case 0:
        ///   CaseZero();
        ///   break;
        ///case 1:
        ///   CaseOne();
        ///   break;
        ///default:
        ///   CaseOthers();
        ///   break;
        ///}.
        /// </summary>
        internal static string SwitchStatement1 {
            get {
                return ResourceManager.GetString("SwitchStatement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch (i) {
        ///case 0:
        ///   CaseZero();
        ///case 1:
        ///   CaseZeroOrOne();
        ///default:
        ///   CaseAny();
        ///}.
        /// </summary>
        internal static string SwitchStatement2 {
            get {
                return ResourceManager.GetString("SwitchStatement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch (i) {
        ///case 0:
        ///   CaseZero();
        ///   goto case 1;
        ///case 1:
        ///   CaseZeroOrOne();
        ///   goto default;
        ///default:
        ///   CaseAny();
        ///   break;
        ///}.
        /// </summary>
        internal static string SwitchStatement3 {
            get {
                return ResourceManager.GetString("SwitchStatement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch (i) {
        ///case 0:
        ///   CaseZero();
        ///   break;
        ///case 1:
        ///   CaseOne();
        ///   break;
        ///case 2:
        ///default:
        ///   CaseTwo();
        ///   break;
        ///}.
        /// </summary>
        internal static string SwitchStatement4 {
            get {
                return ResourceManager.GetString("SwitchStatement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch (i) {
        ///default:
        ///   CaseAny();
        ///   break;
        ///case 1:
        ///   CaseZeroOrOne();
        ///   goto default;
        ///case 0:
        ///   CaseZero();
        ///   goto case 1;
        ///}.
        /// </summary>
        internal static string SwitchStatement5 {
            get {
                return ResourceManager.GetString("SwitchStatement5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch (i) {
        ///case 0:
        ///   while (true) F();
        ///case 1:
        ///   throw new ArgumentException();
        ///case 2:
        ///   return;
        ///}.
        /// </summary>
        internal static string SwitchStatement6 {
            get {
                return ResourceManager.GetString("SwitchStatement6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch (command.ToLower()) {
        ///   case &quot;run&quot;:
        ///      DoRun();
        ///      break;
        ///   case &quot;save&quot;:
        ///      DoSave();
        ///      break;
        ///   case &quot;quit&quot;:
        ///      DoQuit();
        ///      break;
        ///   default:
        ///      InvalidCommand(command);
        ///      break;
        ///   }.
        /// </summary>
        internal static string SwitchStatement7 {
            get {
                return ResourceManager.GetString("SwitchStatement7", resourceCulture);
            }
        }
    }
}
