//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutaParser.Tests.Lexical {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lexical {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lexical() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutaParser.Tests.Lexical.Lexical", typeof(Lexical).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #if Debug
        ///         CheckConsistency();
        ///         #if Trace
        ///            WriteToLog(this.ToString());
        ///         #endif
        ///      #endif
        ///.
        /// </summary>
        internal static string PpConditional1 {
            get {
                return ResourceManager.GetString("PpConditional1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #if Debug
        ///         CheckConsistency();
        ///      #else
        ///         /* Do something else
        ///      #endif
        ///.
        /// </summary>
        internal static string PpConditional2 {
            get {
                return ResourceManager.GetString("PpConditional2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #if Debug
        ///      world
        ///#else
        ///      Nebraska
        ///#endif
        ///.
        /// </summary>
        internal static string PpConditional3 {
            get {
                return ResourceManager.GetString("PpConditional3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #if X
        ///   /*
        ///#else
        ///   /* */ class Q { }
        ///#endif
        ///.
        /// </summary>
        internal static string PpConditional4 {
            get {
                return ResourceManager.GetString("PpConditional4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #if Debug
        ///      world
        ///#elif Trace
        ///      Alabama
        ///#else
        ///      Nebraska
        ///#endif
        ///.
        /// </summary>
        internal static string PpConditional5 {
            get {
                return ResourceManager.GetString("PpConditional5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #if Debug
        ///      world
        ///#else
        ///      Nebraska
        ///#elif Trace
        ///      Alabama
        ///#endif
        ///.
        /// </summary>
        internal static string PpConditional6 {
            get {
                return ResourceManager.GetString("PpConditional6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;hello, world&quot;.
        /// </summary>
        internal static string StringLiteral1 {
            get {
                return ResourceManager.GetString("StringLiteral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;one
        ///two
        ///three&quot;.
        /// </summary>
        internal static string StringLiteral10 {
            get {
                return ResourceManager.GetString("StringLiteral10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Joe said &quot;Hello&quot; to me&quot;.
        /// </summary>
        internal static string StringLiteral11 {
            get {
                return ResourceManager.GetString("StringLiteral11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;Joe said &quot;Hello&quot; to me&quot;.
        /// </summary>
        internal static string StringLiteral12 {
            get {
                return ResourceManager.GetString("StringLiteral12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;one
        ///two
        ///three&quot;.
        /// </summary>
        internal static string StringLiteral13 {
            get {
                return ResourceManager.GetString("StringLiteral13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;hello, world&quot;.
        /// </summary>
        internal static string StringLiteral2 {
            get {
                return ResourceManager.GetString("StringLiteral2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;hello \t world&quot;.
        /// </summary>
        internal static string StringLiteral3 {
            get {
                return ResourceManager.GetString("StringLiteral3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;hello \t world&quot;.
        /// </summary>
        internal static string StringLiteral4 {
            get {
                return ResourceManager.GetString("StringLiteral4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Joe said \&quot;Hello\&quot; to me&quot;.
        /// </summary>
        internal static string StringLiteral5 {
            get {
                return ResourceManager.GetString("StringLiteral5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;Joe said &quot;&quot;Hello&quot;&quot; to me&quot;.
        /// </summary>
        internal static string StringLiteral6 {
            get {
                return ResourceManager.GetString("StringLiteral6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\\\\server\\share\\file.txt&quot;.
        /// </summary>
        internal static string StringLiteral7 {
            get {
                return ResourceManager.GetString("StringLiteral7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;\\server\share\file.txt&quot;.
        /// </summary>
        internal static string StringLiteral8 {
            get {
                return ResourceManager.GetString("StringLiteral8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;one\r\ntwo\r\nthree&quot;.
        /// </summary>
        internal static string StringLiteral9 {
            get {
                return ResourceManager.GetString("StringLiteral9", resourceCulture);
            }
        }
    }
}
