//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nuta.Parser.Css.Tests.Syntactic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Syntactic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syntactic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nuta.Parser.Css.Tests.Syntactic.Syntactic", typeof(Syntactic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen, embossed, print and (resolution: 90dpi).
        /// </summary>
        internal static string MediaQueryList1 {
            get {
                return ResourceManager.GetString("MediaQueryList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tv and (scan: progressive), handheld and (grid) and (device-max-height: 7em).
        /// </summary>
        internal static string MediaQueryList10 {
            get {
                return ResourceManager.GetString("MediaQueryList10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen and (color), projection and (color).
        /// </summary>
        internal static string MediaQueryList2 {
            get {
                return ResourceManager.GetString("MediaQueryList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only screen and (color), (orientation: portrait).
        /// </summary>
        internal static string MediaQueryList3 {
            get {
                return ResourceManager.GetString("MediaQueryList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aural and (device-aspect-ratio: 16/9), speech and (min-device-width: 800px).
        /// </summary>
        internal static string MediaQueryList4 {
            get {
                return ResourceManager.GetString("MediaQueryList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print and (min-width: 25cm), screen and (min-width: 400px) and (max-width: 700px).
        /// </summary>
        internal static string MediaQueryList5 {
            get {
                return ResourceManager.GetString("MediaQueryList5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to handheld and (min-width: 20em), screen and (min-width: 20em).
        /// </summary>
        internal static string MediaQueryList6 {
            get {
                return ResourceManager.GetString("MediaQueryList6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen and (device-width: 800px), screen and (device-height: 600px).
        /// </summary>
        internal static string MediaQueryList7 {
            get {
                return ResourceManager.GetString("MediaQueryList7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all and (min-color: 1), not screen and (color).
        /// </summary>
        internal static string MediaQueryList8 {
            get {
                return ResourceManager.GetString("MediaQueryList8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print and (monochrome), print and (min-resolution: 300dpi), print and (min-resolution: 118dpcm).
        /// </summary>
        internal static string MediaQueryList9 {
            get {
                return ResourceManager.GetString("MediaQueryList9", resourceCulture);
            }
        }
    }
}
